---
title: "Better Scientific Software fellowship"
author: "Frederick J. Boehm"
date: "10/2/2019"
output: html_document
---

## Application Format

### Experience:

*Describe your work relevant to scientific software (1000 - 1500 characters).*
    
    
*Describe your background and experience relevant to being a BSSw Fellow (1000 - 1500 characters).*

### Proposed work and impact:

*What would you do as a BSSw Fellow? (1000 - 1500 characters).*
    
    
*What impact do you foresee from your efforts? (1000 - 1500 characters).*
    
    
*Which BSSw focus areas and subtopics apply to your proposed work? Specify all that apply. See https://bssw.io for a list of focus areas and subtopics (e.g., Focus Area: Planning; Subtopic: Requirements).*

### Extra info

Q&A Webinar about the BSSw Fellowship Program

    Friday, September 20, 2019, 1:00-2:00 pm EDT
    Please subscribe to our mailing list to receive further details, including telecon information for the Q&A session.

More information, including on-line application

    BSSw Fellowship Program
    Online Application (Submissions Open!)
    Application deadline: Tuesday, October 15, 2019; this is a firm deadline that will not be extended.
