---
title: "Enhancing inclusion of diverse students by training future educators"
author: "Frederick J. Boehm, Ana Dyreson, "
date: "11/8/2019"
output: github_document
params:
  lastmod: !r lubridate::now()
---

Last modified: `r params$lastmod`.

We present a curriculum for a diversity-promoting professional development course for future college instructors. We implemented the curriculum in both in-person and online formats. Weekly class meetings focused on activities and discussions of teaching practices that encourage and support the increasingly diverse student body in higher education. Topics included understanding the dimensions of diversity, practicing strategies to combat microaggressions in real time, reviewing pedagological approaches to support inclusivity, and exploring data and research to support classroom practices. By targeting our classes at current graduate students who wish to become professors, we aim to effect institutional change over many years. We conclude the presentation with lessons learned and future directions.

